### ISSUE TITLE
openstick-startup-diagnose脚本的问题

### ISSUE THREAD

**Issue by Zy143L** [hyx0329/openstick-failsafe-guard#1]
https://github.com/hyx0329/openstick-failsafe-guard/blob/0e4fc4ad48cb681082fc2f4d60eec795e9f92d72/openstick-startup-diagnose/openstick-startup-diagnose.sh#L52

### 更换系统语言后 会导致 connected变成已连接 导致字符串过滤返回值错误

![image](https://user-images.githubusercontent.com/21352718/187615071-8642e9e2-b81e-4388-9f38-23daf279587b.png)

**Comment by hyx0329** [comment]
should be fixed by 1944c5fb47b92e8536a820827d8e6131ba7c2553
